#!/usr/bin/env bash

last=""
for dir in *; do
    files=($dir/*)
    if [ -z $last ]; then
        last=${files[-1]}
        continue
    fi
    first=${files[0]}
    # echo $last $first
    if [[ $last =~ (.*)/.*([0-9])9999\.JPG ]]; then
        dir1=${BASH_REMATCH[1]}
        num1=${BASH_REMATCH[2]}
        if [[ $first =~ (.*)/.*([0-9])0001\.JPG ]]; then
            dir2=${BASH_REMATCH[1]}
            num2=${BASH_REMATCH[2]}
            if [[ $(($num1+1)) == $num2 ]]; then
                # echo are sequential
                mkdir ${dir1}_$dir2
                mv $dir1/* ${dir1}_$dir2
                mv $dir2/* ${dir1}_$dir2
            fi
        fi
    fi

    last=${files[-1]}
done

find . -type d -empty -delete