#!/usr/bin/env bash

# https://unix.stackexchange.com/questions/92447/bash-script-to-get-ascii-values-for-alphabet
ord() {
  LC_CTYPE=C printf '%d' "'$1"
}

last=""
for dir in *; do
    files=($dir/*)

    # set last to last image of first folder and continue with second folder
    if [ -z $last ]; then
        last=${files[-1]}
        continue
    fi

    first=${files[0]}
    echo $last $first
    if [[ $last =~ (.*)/G([A-Z]*)([0-9]*)9999\.JPG ]]; then
        dir1=${BASH_REMATCH[1]}
        cha1=${BASH_REMATCH[2]: -1}
        num1=${BASH_REMATCH[3]}
        if [[ $first =~ (.*)/G([A-Z]*)([0-9]*)0001\.JPG ]]; then
            dir2=${BASH_REMATCH[1]}
            cha2=${BASH_REMATCH[2]: -1}
            num2=${BASH_REMATCH[3]}
            echo $dir1 $num1 $cha1
            echo $dir2 $num2 $cha2
            if [[ $(($num1+1)) == $num2 ]] || [[ $(($(ord $cha1)+1)) == $(ord $cha2) ]]; then
                # echo are sequential
                mkdir ${dir1}_$dir2
                mv $dir1/* ${dir1}_$dir2
                mv $dir2/* ${dir1}_$dir2
            fi
        fi
    fi

    last=${files[-1]}
done

find . -type d -empty -delete