#!/usr/bin/env bash
(
    DIR="$HOME/Pictures/streetview/neue_bilder_unsortiert/$(date '+%Y-%m-%dT%H%M%S')_gopro8"
    rsync -Pavh --info=progress2 --info=name0 --stats --progress ./* $DIR

    cd $DIR
    if [ $? -eq 0 ]; then
        mvhere_gopro
    fi
)