#!/usr/bin/env python3

import sys

import ffmpeg_progress_yield
from tqdm import tqdm

with tqdm(
    total=100,
    position=1,
    desc="Running ffmpeg",
    dynamic_ncols=True,
) as pbar:
    for progress in ffmpeg_progress_yield.FfmpegProgress(["ffmpeg"] + sys.argv[1:]).run_command_with_progress():
        pbar.update(progress - pbar.n)

