#!/usr/bin/env bash

find -- * -maxdepth 0 -type d | while read -r dir; do
    echo "'$dir'"
    # if folder empty, dont delete at end, nor loop through it
    if [ "$(find "${dir}" | wc -l)" -ne 0 ]; then
        echo "Empty"
        # continue
    fi

    (
        cd "$dir" || echo "error, $dir"
        find -- * -maxdepth 0 -type d | while read -r sub_d; do
            echo "$dir"_"$sub_d"
            mv -n "$sub_d" ../"$dir"_"$sub_d"
        done
    )

    # delete folder if now empty
    rmdir "$dir" --ignore-fail-on-non-empty
done
