#!/usr/bin/env bash

find * -maxdepth 0 -type d | while read dir; do
    # if folder empty, dont delete at end, nor loop through it
    if [ -z "$(ls -A "${dir}")" ]; then
        echo "Empty"
        continue
    fi

    (
        cd "$dir"
        find * -maxdepth 0 -type d | while read sub_d; do
            echo "$dir"_"$sub_d"
            mv -n "$sub_d" ../"$dir"_"$sub_d"
        done
    )

    # delete folder if now empty
    rmdir "$dir" --ignore-fail-on-non-empty
done
