#!/usr/bin/env bash
trap kill_sem INT

function kill_sem() {
        for s in ~/.parallel/semaphores/id-$$/*@*;
        do
                kill -15 -- -$(basename ${s%%@*})
        done
}

find * -maxdepth 0 -type f -name "*.mp4" -print0 | while IFS= read -r -d '' file; do
    echo "file = $file"
    sem --no-notice --id $$ --lb -j $(grep -c ^processor /proc/cpuinfo) gen_thumbs "'${file}'" $1
done
sem --no-notice --id $$ --wait
