#!/usr/bin/env bash
trap kill_sem INT

function kill_sem() {
    for s in ~/.parallel/semaphores/id-$$/*@*;
    do
        kill -15 -- -"$(basename "${s%%@*}")"
    done
}



find -- * -maxdepth 0 -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.MOV" -o -name "*.mov" \) -print0 | sort -hz "${1:-" "}" | while IFS= read -r -d '' file; do
    sem --id $$ --lb -j "$(grep -c ^processor /proc/cpuinfo)" nice -n 20 gen_thumbs "\"${file}\"" 4 "-n"
    sem --id $$ --lb -j "$(grep -c ^processor /proc/cpuinfo)" nice -n 20 gen_thumbs "\"${file}\"" 11 "-n" backdrop
done
sem --id $$ --wait
wait
