#!/usr/bin/env bash

# make callable from anywhere
cd "$( dirname "${BASH_SOURCE[0]}" )"

state_json=$(curl -s --connect-timeout 1 --max-time 1 --retry 60 --retry-delay 0 --retry-max-time 60 -X GET --url $(cat ~/settings/hue_lights_secret)/lights/$1)
is_on=$(echo $state_json | jq -r '.state.on')
light_name=$(echo $state_json | jq -r '.name')

if [ -z ${2} ]; then
    if [ $is_on == "true" ]; then
        next_on_off_state="false"
    elif [ $is_on == "false" ]; then
        next_on_off_state="true"
    fi
else
    if [ $2 == "on" ]; then
        next_on_off_state="true"
    elif [ $2 == "off" ]; then
        next_on_off_state="false"
    else
        next_on_off_state=$2
    fi
fi

post_return=$(curl -s --connect-timeout 1 --max-time 1 --retry 60 --retry-delay 0 --retry-max-time 60 -X PUT --data "{\"on\":$next_on_off_state}" --url $(cat ~/settings/hue_lights_secret)/lights/$1/state)
success=$(echo ${post_return:1:-1} | jq -r '.success')

if [[ "null" != $success ]]; then
    echo -n \"$light_name\"
    if [ -z ${2} ]; then
        echo -n " toggled to "
    else
        echo -n " is now "
    fi
    if [ $next_on_off_state == "true" ]; then
        echo on
    else
        echo off
    fi
else
    echo failed to change light $1
    exit 1
fi

exit 0
