#!/usr/bin/env bash

disc_free.py

running=$(ls *.log 2>/dev/null|wc -l)
remaining_mp4=$(ls *.mp4 2>/dev/null|wc -l)
remaining_mkv=$(ls *.mkv 2>/dev/null|wc -l)
remaining=$(($remaining_mp4 + $remaining_mkv))
done_mp4=$(ls normalized/*.mp4 2>/dev/null|wc -l)
done_mkv=$(ls normalized/*.mkv 2>/dev/null|wc -l)
done=$(($done_mp4 + $done_mkv))
total=$(echo $done + $remaining|bc)
waiting=$(echo $remaining - $running|bc)

if [ $running -gt 0 ] ; then
    if [ $total -gt 0 ] ; then
        echo $running Running = $(echo "scale=2; 100 * $running / $total" | bc ) %|figlet -kct -f standard
    else
        echo $running Running|figlet -kct -f standard
    fi
fi
if [ $waiting -gt 0 ] ; then
    echo $waiting Waiting = $(echo "scale=2; 100 * $waiting / $total" | bc ) %|figlet -kct -f standard
fi
if [ $total -gt 0 ] ; then
    if [ $done -gt 0 ] ; then
        echo $done Done = $(echo "scale=2; 100 * $done / $total" | bc ) %|figlet -kct -f standard
    fi
fi

width=$(echo $COLUMNS / 2 | bc)
var="list_watch_reaminin_output"
rm -f $var
touch $var
find . -maxdepth 1 \( -name "*.log" \) | while read fname; do
    tail_log=$(tail -n 1 "${fname}" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")
    combined_line=$(echo "$tail_log @ ${fname}")
    combined_line="${combined_line/\%\|  /\%\|MM}"
    combined_line="${combined_line/\%\|/\%@\|}"
    combined_line="${combined_line/\| /\|@}"
    combined_line="${combined_line/\|MM/\|  }"
    combined_line="${combined_line/\/100 \[/\/100@\[}"
    combined_line="${combined_line/Second Pass: /       Second Pass: }"

    combined_line="${combined_line/Stream 1\/1:/Stream         1\/1:}"
    combined_line="${combined_line/Stream 1\/2:/Stream        1.\/2:}"
    combined_line="${combined_line/Stream 2\/2:/Stream         2\/2:}"
    combined_line="${combined_line/Stream 1\/3:/Stream       1..\/3:}"
    combined_line="${combined_line/Stream 2\/3:/Stream        2.\/3:}"
    combined_line="${combined_line/Stream 3\/3:/Stream         3\/3:}"
    combined_line="${combined_line/Stream 1\/4:/Stream      1...\/4:}"
    combined_line="${combined_line/Stream 2\/4:/Stream       2..\/4:}"
    combined_line="${combined_line/Stream 3\/4:/Stream        3.\/4:}"
    combined_line="${combined_line/Stream 4\/4:/Stream         4\/4:}"
    combined_line="${combined_line/Stream 1\/5:/Stream     1....\/5:}"
    combined_line="${combined_line/Stream 2\/5:/Stream      2...\/5:}"
    combined_line="${combined_line/Stream 3\/5:/Stream       3..\/5:}"
    combined_line="${combined_line/Stream 4\/5:/Stream        4.\/5:}"
    combined_line="${combined_line/Stream 5\/5:/Stream         5\/5:}"
    combined_line="${combined_line/Stream 1\/6:/Stream    1.....\/6:}"
    combined_line="${combined_line/Stream 2\/6:/Stream     2....\/6:}"
    combined_line="${combined_line/Stream 3\/6:/Stream      3...\/6:}"
    combined_line="${combined_line/Stream 4\/6:/Stream       4..\/6:}"
    combined_line="${combined_line/Stream 5\/6:/Stream        5.\/6:}"
    combined_line="${combined_line/Stream 6\/6:/Stream         6\/6:}"
    combined_line="${combined_line/Stream 1\/7:/Stream   1......\/7:}"
    combined_line="${combined_line/Stream 2\/7:/Stream    2.....\/7:}"
    combined_line="${combined_line/Stream 3\/7:/Stream     3....\/7:}"
    combined_line="${combined_line/Stream 4\/7:/Stream      4...\/7:}"
    combined_line="${combined_line/Stream 5\/7:/Stream       5..\/7:}"
    combined_line="${combined_line/Stream 6\/7:/Stream        6.\/7:}"
    combined_line="${combined_line/Stream 7\/7:/Stream         7\/7:}"
    combined_line="${combined_line/Stream 1\/8:/Stream  1.......\/8:}"
    combined_line="${combined_line/Stream 2\/8:/Stream   2......\/8:}"
    combined_line="${combined_line/Stream 3\/8:/Stream    3.....\/8:}"
    combined_line="${combined_line/Stream 4\/8:/Stream     4....\/8:}"
    combined_line="${combined_line/Stream 5\/8:/Stream      5...\/8:}"
    combined_line="${combined_line/Stream 6\/8:/Stream       6..\/8:}"
    combined_line="${combined_line/Stream 7\/8:/Stream        7.\/8:}"
    combined_line="${combined_line/Stream 8\/8:/Stream         8\/8:}"
    combined_line="${combined_line/Stream 1\/9:/Stream 1........\/9:}"
    combined_line="${combined_line/Stream 2\/9:/Stream  2.......\/9:}"
    combined_line="${combined_line/Stream 3\/9:/Stream   3......\/9:}"
    combined_line="${combined_line/Stream 4\/9:/Stream    4.....\/9:}"
    combined_line="${combined_line/Stream 5\/9:/Stream     5....\/9:}"
    combined_line="${combined_line/Stream 6\/9:/Stream      6...\/9:}"
    combined_line="${combined_line/Stream 7\/9:/Stream       7..\/9:}"
    combined_line="${combined_line/Stream 8\/9:/Stream        8.\/9:}"
    combined_line="${combined_line/Stream 9\/9:/Stream         9\/9:}"

    echo "${combined_line}" >> $var
done
echo "" >> $var

column -t -s "@" $var
rm -f $var

echo ""
echo $PWD
screen -ls