#!/usr/bin/env bash

# https://unix.stackexchange.com/a/87608/408771
mv *GOPRO/* . -n 2>/dev/null # fail silently

find . -type d -empty -delete

exiftool '-Directory<DateTimeOriginal' -d ./%Y-%m-%d_gopro8 *.JPG
exiftool '-Directory<CreateDate' -d ./%Y-%m-%d_gopro8 *.JPG

find . -type d -empty -delete

for d in $(find * -maxdepth 0 -type d); do
    (
        cd $d
        echo "$d"
        mv */**/*.JPG . -n 2>/dev/null
        for i in {000..999}; do
            mkdir --parent D_$i
            mv G$i*.JPG D_$i 2>/dev/null
        done
        find . -type d -empty -delete
    )
    find . -type d -empty -delete
done
find . -type d -empty -delete