#!/usr/bin/env bash

trap kill_sem INT

function kill_sem() {
    for s in ~/.parallel/semaphores/id-$$/*@*;
    do
        kill -15 -- -$(basename ${s%%@*})
    done
    exit
}

max_threads=${1:-12}

cpus=$(grep -c ^processor /proc/cpuinfo)
threads=$([ $cpus -le "$max_threads" ] && echo "$cpus" || echo "$max_threads")

find . -maxdepth 1 \( -iname "*.ogg" -o -iname "*.mkv" -o -iname "*.mp4" -o -iname "*.m4a" -o -iname "*.opus" -o -iname "*.webm" \) -print0 | xargs -0 normalize.py -t $threads "${@:2}"
