#!/usr/bin/env bash

codec=$(ffprobe -v error -select_streams a:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "${1}")
sample_rate=$(ffprobe -v error -select_streams a -of default=noprint_wrappers=1:nokey=1 -show_entries stream=sample_rate "${1}"|head -n1)
ffmpeg-normalize -pr -f -ar "${sample_rate}" --extension mp4 -c:a "${codec}" "${1}"
