#!/usr/bin/env bash

if [ "$#" -le 1 ]; then
    echo "no language code given, moving \"${1}\" anyway assuming it is labeled correctly"
elif [ "$#" -le 2 ]; then
    ffmpeg_set_language "${1}" "${2}"
elif [ "$#" -le 3 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}"
elif [ "$#" -le 4 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}"
elif [ "$#" -le 5 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}" "${5}"
elif [ "$#" -le 6 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}" "${5}" "${6}"
elif [ "$#" -le 7 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}"
elif [ "$#" -le 8 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}"
elif [ "$#" -le 9 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}"
elif [ "$#" -le 10 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}"
elif [ "$#" -le 11 ]; then
    ffmpeg_set_language "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}"
else
    echo "too many arguments"
    exit
fi

wait

bn="$(basename "${1/.mkv/}")"
# echo $bn
find . -name "$bn*.vtt" -exec mv -vn {} /media/wd4-r1/data/filme_neu/ok_subtitles \;
find . -name "$bn*.srt" -exec mv -vn {} /media/wd4-r1/data/filme_neu/ok_subtitles \;
touch "${1}"_moved_away
mv -vn "${1}" /media/wd4-r1/data/filme_neu/ok_subtitles
/media/wd4-r1/data/filme_neu/mv_ok_subtitles.sh
