#!/usr/bin/env bash

bn="$(basename "${1/.mkv/}")"
# echo $bn
find . -name "$bn*.vtt" -exec mv -vn {} /media/wd4-r1/data_36/filme_neu/ok_subtitles \;
find . -name "$bn*.srt" -exec mv -vn {} /media/wd4-r1/data_36/filme_neu/ok_subtitles \;

pattern="\.?/?(.*)_([0-9]{4})(.*)\.mkv|mp4|iso"
if [[ $1 =~ $pattern ]]; then
    movie_name="${BASH_REMATCH[1]}"
    year="${BASH_REMATCH[2]}"
    mkdir -p moved_away
    touch "moved_away/$movie_name.${year}_${BASH_REMATCH[3]}"_moved_away
fi

mkdir -p /media/wd4-r1/data_36/filme_neu/ok_subtitles
mv -vn "${1}" /media/wd4-r1/data_36/filme_neu/ok_subtitles
/media/wd4-r1/data_36/filme_neu/mv_ok_subtitles.sh
