#!/usr/bin/env python3
"""
Docstring for yt-dlp_all_audio
"""

import argparse
import multiprocessing as mp
import pathlib
import subprocess
import sys
import traceback
from collections import defaultdict
from inspect import currentframe, getframeinfo, stack

import tqdm
import yt_dlp


def eprint(*args, **kwargs) -> None:  # type: ignore
    """
    eprint prints to stderr with info of the caller.
    """
    print(f"{stack()[1][1]}:{stack()[1][2]};{stack()[1][3]}", *args, file=sys.stderr, **kwargs)


def print_lineno() -> str:
    """Get line number of the caller in it's source code."""
    cf = currentframe()
    if not cf:
        return "no_frame_found:?"
    lineno = cf.f_back.f_lineno if cf.f_back else "?"
    return f"{getframeinfo(cf).filename}:{lineno}"


def merge(files: list[str], out_name: str) -> str:
    """
    merge multiple files into one using mkvmerge

    :param files: List of file paths to merge
    :type files: list[str]
    :param out_name: Output file path
    :return out_name: Output file path
    """

    commands = ["mkvmerge", "-v", "-o", out_name] + files

    try:
        sub_process_result = subprocess.run(
            commands,
            capture_output=True,
            check=False
        )
        status_ok = sub_process_result.returncode == 0
        warning = sub_process_result.returncode == 1
        error = sub_process_result.returncode not in (0, 1)

        if not status_ok:
            sub_process_std_out = sub_process_result.stdout.decode("utf-8", errors="ignore")
            sub_process_std_err = sub_process_result.stderr.decode("utf-8", errors="ignore")
            print(print_lineno(), f"{sub_process_result.returncode=}")

            if warning:
                sub_process_std_err = sub_process_std_err.replace("\\n", "warning:    \n")
                sub_process_std_out = sub_process_std_out.replace("\\n", "warning:    \n")
                print(print_lineno(), f"\nwarning:    {sub_process_std_out=}")
                print(print_lineno(), f"\nwarning:    {sub_process_std_err=}")

            if error:
                print(print_lineno(), f"{sub_process_std_out=}")
                print(print_lineno(), f"{sub_process_std_err=}")
                sys.exit(3)
    except Exception as e:  # pylint: disable=W0718  # Catching broad exception
        traceback.print_exc()
        print(type(e), e)
        sys.exit(2)

    for path in files:
        pathlib.Path(path).unlink()

    return out_name


def set_track_title(temp_name: str, out_name: str, title: str) -> str:
    """
    set_track_title sets the title of the video track in the output file.

    Arguments:
        temp_name -- input file name, is removed after processing
        out_name -- output file name
        title -- title to set for the video track

    Returns:
        out_name -- same as argument
    """
    commands = ["mkvmerge", "-v", "-o", out_name, "--track-name", f"0:{title}", temp_name]

    try:
        sub_process_result = subprocess.run(
            commands,
            capture_output=True,
            check=False
        )
        status_ok = sub_process_result.returncode == 0
        warning = sub_process_result.returncode == 1
        error = sub_process_result.returncode != 0 and sub_process_result.returncode != 1

        if not status_ok:
            sub_process_std_out = sub_process_result.stdout.decode("utf-8", errors="ignore")
            sub_process_std_err = sub_process_result.stderr.decode("utf-8", errors="ignore")
            print(print_lineno(), f"{sub_process_result.returncode=}")

            if warning:
                sub_process_std_err = sub_process_std_err.replace("\\n", "warning:    \n")
                sub_process_std_out = sub_process_std_out.replace("\\n", "warning:    \n")
                print(print_lineno(), f"\nwarning:    {sub_process_std_out=}")
                print(print_lineno(), f"\nwarning:    {sub_process_std_err=}")

            if error:
                print(print_lineno(), f"{sub_process_std_out=}")
                print(print_lineno(), f"{sub_process_std_err=}")
                sys.exit(3)
    except Exception as e:  # pylint: disable=W0718  # Catching broad exception
        traceback.print_exc()
        print(type(e), e)
        sys.exit(2)

    pathlib.Path(temp_name).unlink()
    return out_name


def download_format_wrap(args_tuple: tuple[tuple[str, str], int, str, str, float, pathlib.Path | None, pathlib.Path | None, int]) -> str:
    """
    download_format_wrap wraps the download_format function so its signature matches the expected signature for multiprocessing.

    Arguments:
        args_tuple -- A tuple containing the arguments for download_format.

    Returns:
        The result of download_format.
    """
    format_tuple, max_format_str_length, url, title, ratelimit, archive_path, cookies_path, concurrent_fragments = args_tuple
    return download_format(format_tuple, max_format_str_length, url, title, ratelimit, archive_path, cookies_path, concurrent_fragments)


def download_format(format_tuple: tuple[str, str], max_format_str_length: int, url: str, title: str, ratelimit: float, archive_path: pathlib.Path | None = None, cookies_path: pathlib.Path | None = None, concurrent_fragments: int = 42) -> str:
    specified_format, track_title = format_tuple
    out_name = f"{title}.{specified_format}.mkv"
    ydl_opts = {
        "ignoreerrors": False,
        "format": specified_format,
        "outtmpl": out_name,
        "concurrent_fragment_downloads": concurrent_fragments,
        "ratelimit": ratelimit / concurrent_fragments,  # bytes per second
        "fragment_retries": float("inf"),
        "skip_unavailable_fragments": False,
        'postprocessors': [{
            'actions': [(
                yt_dlp.postprocessor.metadataparser.MetadataParserPP.replacer,
                'id',
                '(.+)',
                f"\\1∕{specified_format}"
            )],
            'key': 'MetadataParser',
            'when': 'pre_process'
        }],
        "overwrites": False,
        "noprogress": False,
        "progress": True,
        "quiet": True,
        "consoletitle": True,
        "verbose": False,
        "progress_template": {"download": f"[{specified_format:{max_format_str_length}}] %(progress._percent_str)s of %(progress._total_bytes_str)s (~%(progress._total_bytes_estimate_str)s) at %(progress._speed_str)s ETA %(progress._eta_str)s (%(progress._elapsed_str)s)"},
    }

    if archive_path is not None:
        ydl_opts["download_archive"] = str(archive_path)
    if cookies_path is not None:
        ydl_opts["cookiefile"] = str(cookies_path)

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        error_code = ydl.download([url])
        if error_code != 0:
            print(f"{error_code=}")
            raise RuntimeError(f"Download failed for {url=} with {specified_format=}, {error_code=}")

    # return set_track_title(out_name, out_name, track_title)
    return track_title


def download_subs(url: str, outtmpl_yt_dlp__title: str, archive_path: pathlib.Path | None = None, cookies_path: pathlib.Path | None = None) -> None:
    """
    download_subs downloads subtitles for a given video URL.

    Arguments:
        url -- The URL of the video to download subtitles for.
        outtmpl_yt_dlp__title -- The title to use for the downloaded subtitle file.
    """
    ydl_opts = {
        "ignoreerrors": True,
        "writesubtitles": True,
        "allsubtitles": True,
        "skip_download": True,
        "outtmpl": outtmpl_yt_dlp__title,
        "concurrent_fragment_downloads": 42,
        "overwrites": False,
        "noprogress": False,
        "progress": True,
        "quiet": True,
        "consoletitle": True,
        "verbose": False,
    }

    if archive_path is not None:
        ydl_opts["download_archive"] = str(archive_path)
    if cookies_path is not None:
        ydl_opts["cookiefile"] = str(cookies_path)

    with yt_dlp.YoutubeDL(params=ydl_opts) as ydl:
        error_code = ydl.download([url])
        print(error_code)


def get_download_ids(url: str, archive_path: pathlib.Path | None = None, cookies_path: pathlib.Path | None = None) -> tuple[list[tuple[str, str]], str]:
    """
    get_download_ids fetches the download ids and title for a given url.

    Arguments:
        url -- The URL to fetch download IDs from.
        archive_path -- The path to the download archive file.
        cookies_path -- The path to the cookies file.

    Returns:
        structured info
    """
    ydl_opts: dict[str, int | bool | str] = {
        "concurrent_fragment_downloads": 42,
        "overwrites": False,
        "noprogress": False,
        "progress": True,
        "quiet": True,
        "consoletitle": True,
        "verbose": False,
    }

    if archive_path is not None:
        ydl_opts["download_archive"] = str(archive_path)
    if cookies_path is not None:
        ydl_opts["cookiefile"] = str(cookies_path)

    downloadables: list[tuple[str, str]] = []
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=False)

        # info: ydl.sanitize_info makes the info json-serializable
        info = ydl.sanitize_info(info)
        if info is None:
            raise RuntimeError(f"Failed to extract info for {url=}")
        download_formats = info.get("formats", [])
        if download_formats is None:
            raise RuntimeError(f"Failed to extract formats for {url=}")
        video_resolutions: dict[int, set[tuple[str, str]]] = defaultdict(set)
        audio_options: dict[str, list[tuple[str, str]]] = defaultdict(list)

        best_resolution = 0

        # download_format_dict: dict
        for download_format_dict in download_formats:
            language = download_format_dict.get("language", "und")
            format_note = f"[{language}] {download_format_dict.get('format_note', '')}"
            if download_format_dict["audio_ext"] == "none":
                width = download_format_dict.get("width", 1)
                height = download_format_dict.get("height", 1)
                resolution = width * height
                video_resolutions[resolution].add((download_format_dict["format_id"], format_note))
                if best_resolution < resolution:
                    best_resolution = resolution
            else:
                format_id: str = download_format_dict["format_id"]
                unique_name: str = format_note + " - " + format_id
                unique_name = unique_name.rstrip("01233456789").rstrip("-")
                audio_options[unique_name].append((format_id, format_note))

        for unique_name, audio_names in audio_options.items():
            downloadables.append(audio_names[0])

        for video_option in video_resolutions[best_resolution]:
            downloadables.append(video_option)
            # break  # get *all* best resolutions if there are multiple

    title = str(info.get("title", "[Unknown Title]"))
    extractor = info.get("extractor")
    extractor_key = info.get("extractor_key")

    if extractor == extractor_key:
        extractor_key = ""

    if extractor and extractor_key:
        title += f" - {extractor}-{extractor_key} Mediathek"
    elif extractor or extractor_key:
        title += f" - {extractor or extractor_key} Mediathek"

    return downloadables, title


def main(url: str, ratelimit: float, archive_path: pathlib.Path | None = None, concurrent_fragments: int = 42, cookies_path: pathlib.Path = pathlib.Path("cookies.txt")) -> int:
    downloadables_formats, title = get_download_ids(url, archive_path, cookies_path)
    title = title.replace("/", "⧸")

    max_format_str_length = max(len(format_str) for format_str, _ in downloadables_formats)

    download_subs(url, title, archive_path, cookies_path)

    tasks: list[tuple[tuple[str, str], int, str, str, float, pathlib.Path | None, pathlib.Path | None, int]] = []
    for downloadable_format in downloadables_formats:
        tasks.append((downloadable_format, max_format_str_length,  url, title, ratelimit, archive_path, cookies_path, concurrent_fragments))
        dl_fmt = f"'{downloadable_format[0]}'"
        print(f"{dl_fmt:{max_format_str_length+3}} '{downloadable_format[1]}'")

    downloaded_names = []
    try:
        with mp.Pool(processes=1) as mp_pool_download:
            results = mp_pool_download.imap_unordered(download_format_wrap, tasks)
            mp_pool_download.close()  # no more tasks will be added

            for filepath in tqdm.tqdm(results, total=len(tasks), dynamic_ncols=True, unit="file", position=1, desc="Downloading"):
                downloaded_names.append(filepath)
            mp_pool_download.join()  # wait for all tasks to finish

        # merge(downloaded_names, f"{title}.mkv")
    except Exception as e:
        eprint(f"{type(e)=} occurred:\n{e}")
        return 1

    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Use yt-dlp to download movie from e.g. Arte with all languages, subtitles, then use mkvmerge them and set the audio track name")

    parser.add_argument(
        "url",
        type=str,
        help="url of the video",
        metavar="url",
    )

    parser.add_argument(
        "ratelimit",
        type=float,
        help="Maximum download rate in bytes per second, e.g. 6663000",
        metavar="r",
        default="6663000",
        nargs="?",
    )

    parser.add_argument(
        "--download-archive",
        type=pathlib.Path,
        help="Download only videos not listed in the archive file. Record the IDs of all downloaded videos in it",
        metavar="FILE",
        default="archive.yt_dlp_archive",
        nargs="?",
    )

    parser.add_argument(
        "--concurrent-fragments",
        "-N",
        type=int,
        help="Number of fragments of a dash/hlsnative video that should be downloaded concurrently (default is 42)",
        metavar="N",
        default=42,
        nargs="?",
    )

    parser.add_argument(
        "--cookies",
        type=pathlib.Path,
        help="Path to the cookies.txt file for authentication",
        metavar="FILE",
        default="cookies.txt",
        nargs="?",
    )

    parsed_arguments = parser.parse_args()

    argument_url: str = parsed_arguments.url
    argument_ratelimit: float = parsed_arguments.ratelimit
    argument_download_archive: pathlib.Path = parsed_arguments.download_archive
    argument_concurrent_fragments: int = parsed_arguments.concurrent_fragments
    cookies_path: pathlib.Path = parsed_arguments.cookies
    sys.exit(main(argument_url, argument_ratelimit, argument_download_archive, argument_concurrent_fragments, cookies_path))
